#!/usr/bin/env python3
"""Generate scripts/drive_import.gs, a Google Apps Script that copies every open paper into a Drive folder.

Google Drive cannot import a file from a URL, and this project's tooling can only upload files by sending
their bytes inline, which is impractical for hundreds of MB of PDFs. The Apps Script runs inside your Google
account: UrlFetchApp downloads each open copy (Internet Archive / agency links from catalog/papers.csv) and
DriveApp saves it into the target folder. Papers larger than Apps Script's 50 MB response limit are listed in
the log with their link so you can add them by hand.

Usage: python scripts/build_drive_import.py [--folder-id ID]
"""
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_FOLDER = "1zB87Ukso3or-ez0tZ5lGeSl9wfXv60OJ"

TEMPLATE = """/**
 * Copies the open-access papers of the Military Anthropometry project into a Google Drive folder.
 * Generated by scripts/build_drive_import.py from catalog/papers.csv -- do not edit by hand.
 *
 * How to run (once): open https://script.google.com -> New project -> paste this file -> Run `importPapers`
 * and accept the permissions. The run stops after ~5 minutes; run it again and it continues where it left off
 * (files already in the folder are skipped).
 */
const FOLDER_ID = '__FOLDER__';
const MAX_BYTES = 50 * 1024 * 1024; // UrlFetchApp response limit
const PAPERS = __PAPERS__;

function importPapers() {
  const folder = DriveApp.getFolderById(FOLDER_ID);
  const have = {};
  const it = folder.getFiles();
  while (it.hasNext()) have[it.next().getName()] = true;
  const started = Date.now();
  let saved = 0, skipped = 0, tooBig = [], failed = [];
  for (const p of PAPERS) {
    if (have[p.name]) { skipped++; continue; }
    if (Date.now() - started > 5 * 60 * 1000) { Logger.log('Time budget reached; run again to continue.'); break; }
    if (p.mb > 50) { tooBig.push(p); continue; }
    try {
      const res = UrlFetchApp.fetch(p.url, { muteHttpExceptions: true, followRedirects: true });
      const blob = res.getBlob();
      if (res.getResponseCode() !== 200 || blob.getBytes().length < 2000 || blob.getContentType().indexOf('html') >= 0) {
        failed.push(p); continue;
      }
      folder.createFile(blob.setName(p.name));
      saved++;
    } catch (e) { failed.push(p); }
  }
  Logger.log('saved ' + saved + ', already there ' + skipped + ', too big for Apps Script ' + tooBig.length + ', failed ' + failed.length);
  tooBig.forEach(p => Logger.log('TOO BIG (' + p.mb + ' MB), download manually: ' + p.url));
  failed.forEach(p => Logger.log('FAILED: ' + p.url));
}
"""


def main():
    folder = DEFAULT_FOLDER
    if "--folder-id" in sys.argv:
        folder = sys.argv[sys.argv.index("--folder-id") + 1]
    papers = []
    for r in csv.DictReader(open(ROOT / "catalog" / "papers.csv", encoding="utf-8")):
        url = r["open_copy_url"]
        if not r["local_file"] or not url:
            continue
        name = Path(r["local_file"]).name
        papers.append({"name": f"{r['survey_id'] or 'paper'}__{name}", "url": url, "mb": float(r["size_mb"] or 0), "title": r["title"]})
    papers.sort(key=lambda p: p["mb"])
    out = ROOT / "scripts" / "drive_import.gs"
    out.write_text(TEMPLATE.replace("__FOLDER__", folder).replace("__PAPERS__", json.dumps(papers, indent=1, ensure_ascii=False)), encoding="utf-8")
    big = sum(p["mb"] > 50 for p in papers)
    print(f"wrote {out.relative_to(ROOT)}: {len(papers)} papers, {big} over 50 MB")


if __name__ == "__main__":
    main()
