#!/usr/bin/env python3
"""Validate catalog/*.yaml and regenerate the derived catalog files.

Outputs:
  catalog/surveys.csv            one row per survey, links joined with " | "
  catalog/surveys.json           full structured catalog
  catalog/additional_reports.csv
  CATALOG.md                     human-readable master table

Requires: pyyaml
Usage: python scripts/build_catalog.py [--check]
  --check  fail if the generated files are out of date (for CI)
"""
import csv
import io
import json
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CAT = ROOT / "catalog"
REGIONS = [
    "United States",
    "United Kingdom",
    "Canada / Australia / New Zealand",
    "Europe / Other",
    "Asia-Pacific / Middle East / Latin America",
]
CSV_FIELDS = ["row", "id", "region", "entry", "measured", "published", "sample", "dimensions",
              "data_access", "report_access", "licence", "verification", "citations",
              "report_urls", "data_urls", "local_data", "notes"]


def load():
    surveys = yaml.safe_load(open(CAT / "surveys.yaml", encoding="utf-8"))["surveys"]
    extra = yaml.safe_load(open(CAT / "additional_reports.yaml", encoding="utf-8"))["reports"]
    surveys.sort(key=lambda s: s["row"])
    return surveys, extra


def validate(surveys, extra):
    errors = []
    ids = [s["id"] for s in surveys]
    rows = [s["row"] for s in surveys]
    if len(set(ids)) != len(ids):
        errors.append("duplicate ids")
    if sorted(rows) != list(range(1, 50)):
        errors.append(f"entry numbers must be exactly 1..49, got {sorted(rows)}")
    for s in surveys:
        for key in ("id", "row", "region", "entry", "citations", "data_access", "report_access", "verification"):
            if key not in s:
                errors.append(f"{s.get('id')}: missing {key}")
        if s.get("region") not in REGIONS:
            errors.append(f"{s['id']}: unknown region {s.get('region')!r}")
        for d in s.get("data", []):
            if "local" in d and not (ROOT / d["local"]).exists():
                errors.append(f"{s['id']}: local file {d['local']} missing")
            if "url" not in d and "local" not in d:
                errors.append(f"{s['id']}: data item needs url or local")
    for r in extra:
        if r.get("related") and r["related"] not in ids:
            errors.append(f"additional report {r['title']!r}: unknown related id {r['related']}")
    if errors:
        raise SystemExit("catalog errors:\n  " + "\n  ".join(errors))


def csv_text(rows, fields):
    buf = io.StringIO()
    w = csv.DictWriter(buf, fieldnames=fields, lineterminator="\n")
    w.writeheader()
    w.writerows(rows)
    return buf.getvalue()


def survey_row(s):
    return {
        **{k: s.get(k, "") for k in CSV_FIELDS},
        "citations": " | ".join(s["citations"]),
        "report_urls": " | ".join(r["url"] for r in s.get("reports", [])),
        "data_urls": " | ".join(d["url"] for d in s.get("data", []) if "url" in d),
        "local_data": " | ".join(d["local"] for d in s.get("data", []) if "local" in d),
    }


def md_cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def md_links(items, with_local=False):
    parts = []
    for it in items:
        if "url" in it:
            parts.append(f"[{md_cell(it['label'])}]({it['url']})")
        elif with_local:
            parts.append(f"{md_cell(it['label'])}")
        if with_local and "local" in it:
            parts[-1] += f" → [`{it['local']}`]({it['local']})"
    return "<br>".join(parts)


def markdown(surveys, extra):
    out = [
        "# Survey catalog",
        "",
        "<!-- Generated by scripts/build_catalog.py from catalog/surveys.yaml. Do not edit by hand. -->",
        "",
        "All 49 military anthropometric surveys, grouped by region. Links marked DTIC use the",
        "`apps.dtic.mil/sti/tr/pdf/<ACC>.pdf` or `apps.dtic.mil/sti/pdfs/<ACC>.pdf` form; both work.",
        "See [`catalog/link_status.csv`](catalog/link_status.csv) for the latest automated link check.",
        "",
        "Legend — **Data**: `public` (downloadable, copy in `data/`), `not public`, `commercial`, `restricted`, `n/a` (summary statistics only).",
        "**Verification**: `verified` (report title page seen), `partly verified`, `not verified` (best available citation only).",
        "",
    ]
    for region in REGIONS:
        out += [f"## {region}", "",
                "| # | Entry | Citation(s) | Study PDFs | Individual-level data | Access | Measured / published | Sample / dimensions | Verification & notes |",
                "|---|---|---|---|---|---|---|---|---|"]
        for s in (s for s in surveys if s["region"] == region):
            access = f"data: **{s['data_access']}**<br>report: {s['report_access']}"
            if s.get("licence"):
                access += f"<br>{md_cell(s['licence'])}"
            when = "<br>".join(x for x in (
                f"measured {s['measured']}" if s.get("measured") else "",
                f"published {s['published']}" if s.get("published") else "") if x)
            size = "<br>".join(md_cell(x) for x in (s.get("sample", ""), s.get("dimensions", "")) if x)
            notes = f"**{s['verification']}**" + (f"<br>{md_cell(s['notes'])}" if s.get("notes") else "")
            out.append("| " + " | ".join([
                str(s["row"]), md_cell(s["entry"]),
                "<br><br>".join(md_cell(c) for c in s["citations"]),
                md_links(s.get("reports", [])) or "—",
                md_links(s.get("data", []), with_local=True) or "—",
                access, when or "—", size or "—", notes,
            ]) + " |")
        out.append("")
    out += ["## Additional relevant reports", "", "| Report | Related entry | Link |", "|---|---|---|"]
    for r in extra:
        out.append(f"| {md_cell(r['title'])} | {r.get('related', '')} | [PDF]({r['url']}) |")
    out.append("")
    return "\n".join(out)


def main():
    check = "--check" in sys.argv
    surveys, extra = load()
    validate(surveys, extra)
    outputs = {
        CAT / "surveys.csv": csv_text([survey_row(s) for s in surveys], CSV_FIELDS),
        CAT / "surveys.json": json.dumps({"surveys": surveys, "additional_reports": extra},
                                         indent=2, ensure_ascii=False) + "\n",
        CAT / "additional_reports.csv": csv_text(
            [{"title": r["title"], "related": r.get("related", ""), "url": r["url"]} for r in extra],
            ["title", "related", "url"]),
        ROOT / "CATALOG.md": markdown(surveys, extra),
    }
    stale = []
    for path, text in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        raise SystemExit("out of date (run scripts/build_catalog.py): " + ", ".join(stale))
    print(f"{len(surveys)} surveys, {len(extra)} additional reports: OK")


if __name__ == "__main__":
    main()
