#!/usr/bin/env python3
"""Build the static website into public/ (used by the Vercel deployment).

public/ contains:
  index.html   searchable, filterable survey catalog (data embedded inline)
  data/        the open datasets, so the site can link to direct downloads
  catalog/     surveys.csv, surveys.json, additional_reports.csv, link_status.csv

Reads catalog/surveys.json (generated by scripts/build_catalog.py) and uses
only the standard library, so no pip install is needed at build time.

Usage: python scripts/build_site.py
"""
import html
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public"

PAGE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Military Anthropometric Surveys</title>
<meta name="description" content="Catalog of 49 military anthropometric surveys with study PDFs and four open datasets.">
<style>
:root{--bg:#fff;--fg:#1a1d21;--muted:#5b6470;--line:#d9dde3;--card:#f6f7f9;--accent:#1f5fbf;--ok:#1b7a3d;--warn:#9a6700;--no:#6b7280}
@media(prefers-color-scheme:dark){:root{--bg:#14161a;--fg:#e8eaed;--muted:#9aa3ae;--line:#2d323a;--card:#1c1f25;--accent:#7fb0ff;--ok:#5fd08a;--warn:#e3b341;--no:#8b94a1}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif}
main{max-width:1000px;margin:0 auto;padding:24px 16px 64px}
h1{font-size:1.6rem;margin:0 0 4px}
.sub{color:var(--muted);margin:0 0 20px}
a{color:var(--accent)}
.controls{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}
input,select{font:inherit;padding:8px 10px;border:1px solid var(--line);border-radius:6px;background:var(--bg);color:var(--fg)}
input{flex:1 1 220px}
.count{color:var(--muted);margin:0 0 12px;font-size:.9rem}
.card{border:1px solid var(--line);border-radius:8px;background:var(--card);padding:14px 16px;margin-bottom:10px}
.card h2{font-size:1.05rem;margin:0 0 4px}
.tags{display:flex;flex-wrap:wrap;gap:6px;margin:6px 0}
.tag{font-size:.75rem;border:1px solid var(--line);border-radius:99px;padding:1px 9px;color:var(--muted)}
.tag.pub{color:var(--ok);border-color:var(--ok)}
.tag.part{color:var(--warn);border-color:var(--warn)}
.meta{color:var(--muted);font-size:.9rem;margin:4px 0}
.cite{font-size:.9rem;margin:6px 0}
ul.links{margin:6px 0 0;padding-left:20px;font-size:.92rem}
.note{font-size:.88rem;color:var(--muted);margin-top:6px}
footer{margin-top:32px;color:var(--muted);font-size:.9rem}
</style>
</head>
<body>
<main>
<h1>Military Anthropometric Surveys</h1>
<p class="sub">__N__ surveys &middot; 4 with free individual-level data &middot;
<a href="catalog/surveys.csv">CSV</a> &middot; <a href="catalog/surveys.json">JSON</a> &middot;
<a href="__REPO__">GitHub</a></p>
<div class="controls">
<input id="q" type="search" placeholder="Search name, author, report number&hellip;" aria-label="Search">
<select id="region" aria-label="Region"><option value="">All regions</option></select>
<select id="data" aria-label="Data access"><option value="">Any data access</option></select>
<select id="ver" aria-label="Verification"><option value="">Any verification</option></select>
</div>
<p class="count" id="count"></p>
<div id="list"></div>
<footer>
<p>Report links on <code>apps.dtic.mil</code> sometimes show a maintenance page; retry later.
Entries marked &ldquo;not verified&rdquo; give only the best available citation.
See <a href="__REPO__/blob/main/CORRECTIONS.md">corrections and open questions</a>.</p>
</footer>
</main>
<script id="catalog" type="application/json">__DATA__</script>
<script>
const surveys = JSON.parse(document.getElementById('catalog').textContent).surveys;
const $ = id => document.getElementById(id);
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const uniq = k => [...new Set(surveys.map(s => s[k]))];
for (const [id, key] of [['region','region'],['data','data_access'],['ver','verification']])
  uniq(key).forEach(v => $(id).insertAdjacentHTML('beforeend', `<option>${esc(v)}</option>`));

function card(s) {
  const links = (s.reports || []).map(r => `<li><a href="${esc(r.url)}" rel="noopener">${esc(r.label)}</a></li>`)
    .concat((s.data || []).map(d => {
      const href = d.local ? d.local : d.url;
      return href ? `<li><strong>Data:</strong> <a href="${esc(href)}">${esc(d.label)}</a></li>` : '';
    })).join('');
  const dcls = s.data_access === 'public' ? 'tag pub' : 'tag';
  const vcls = s.verification === 'verified' ? 'tag pub' : s.verification === 'partly verified' ? 'tag part' : 'tag';
  const meta = [s.measured && 'measured ' + s.measured, s.published && 'published ' + s.published, s.sample, s.dimensions]
    .filter(Boolean).map(esc).join(' &middot; ');
  return `<article class="card"><h2>${s.row}. ${esc(s.entry)}</h2>
  <div class="tags"><span class="tag">${esc(s.region)}</span><span class="${dcls}">data: ${esc(s.data_access)}</span>
  <span class="tag">report: ${esc(s.report_access)}</span><span class="${vcls}">${esc(s.verification)}</span>
  ${s.licence ? `<span class="tag">${esc(s.licence)}</span>` : ''}</div>
  ${meta ? `<p class="meta">${meta}</p>` : ''}
  ${s.citations.map(c => `<p class="cite">${esc(c)}</p>`).join('')}
  ${links ? `<ul class="links">${links}</ul>` : ''}
  ${s.notes ? `<p class="note">${esc(s.notes)}</p>` : ''}</article>`;
}

function render() {
  const q = $('q').value.toLowerCase().trim();
  const f = {region: $('region').value, data_access: $('data').value, verification: $('ver').value};
  const hit = surveys.filter(s =>
    Object.entries(f).every(([k, v]) => !v || s[k] === v) &&
    (!q || JSON.stringify(s).toLowerCase().includes(q)));
  $('count').textContent = `${hit.length} of ${surveys.length} surveys`;
  $('list').innerHTML = hit.map(card).join('') || '<p>No matches.</p>';
}
['q','region','data','ver'].forEach(id => $(id).addEventListener('input', render));
render();
</script>
</body>
</html>
"""


def main():
    catalog = json.loads((ROOT / "catalog" / "surveys.json").read_text(encoding="utf-8"))
    repo = "https://github.com/hfelabs-boop/AnthropometricRepo"
    # "</" inside inline JSON could close the script tag early.
    data = json.dumps(catalog, ensure_ascii=False).replace("</", "<\\/")
    page = (PAGE.replace("__N__", str(len(catalog["surveys"])))
                .replace("__REPO__", html.escape(repo))
                .replace("__DATA__", data))

    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir()
    (OUT / "index.html").write_text(page, encoding="utf-8")
    shutil.copytree(ROOT / "data", OUT / "data")
    (OUT / "catalog").mkdir()
    for name in ("surveys.csv", "surveys.json", "additional_reports.csv", "link_status.csv"):
        shutil.copy(ROOT / "catalog" / name, OUT / "catalog" / name)
    print(f"built {OUT.relative_to(ROOT)}/: {len(catalog['surveys'])} surveys")


if __name__ == "__main__":
    main()
