/**
 * Copies the open-access papers of the Military Anthropometry project into a Google Drive folder.
 * Generated by scripts/build_drive_import.py from catalog/papers.csv -- do not edit by hand.
 *
 * How to run (once): open https://script.google.com -> New project -> paste this file -> Run `importPapers`
 * and accept the permissions. The run stops after ~5 minutes; run it again and it continues where it left off
 * (files already in the folder are skipped).
 */
const FOLDER_ID = '1zB87Ukso3or-ez0tZ5lGeSl9wfXv60OJ';
const MAX_BYTES = 50 * 1024 * 1024; // UrlFetchApp response limit
const PAPERS = [
 {
  "name": "ansur-ii-2012__ANSURII-MFR.pdf",
  "url": "https://tools.openlab.psu.edu/publicData/ANSURII-MFR.pdf",
  "mb": 0.16,
  "title": "Memorandum for Record (ODL)"
 },
 {
  "name": "ansur-1988__ANSUR_88_Codes.pdf",
  "url": "http://mreed.umtri.umich.edu/mreed/downloads/anthro/ansur/ANSUR_88_Codes.pdf",
  "mb": 0.23,
  "title": "ANSUR 88 variable codes (UMTRI)"
 },
 {
  "name": "additional__ADA472617.pdf",
  "url": "https://archive.org/download/DTIC_ADA472617/DTIC_ADA472617.pdf",
  "mb": 0.29,
  "title": "Revised Anthropometric Restrictions for U.S. Navy and Marine Corps aircraft"
 },
 {
  "name": "usaf-1967__Anthropometry.pdf",
  "url": "https://cran.r-project.org/web/packages/Anthropometry/Anthropometry.pdf",
  "mb": 0.29,
  "title": "Anthropometry package manual (CRAN)"
 },
 {
  "name": "us-army-women-1977__ADA056493.pdf",
  "url": "https://archive.org/download/DTIC_ADA056493/DTIC_ADA056493.pdf",
  "mb": 0.66,
  "title": "Summary, White & DeSantis (DTIC)"
 },
 {
  "name": "additional__AD0735101.pdf",
  "url": "https://archive.org/download/DTIC_AD0735101/DTIC_AD0735101.pdf",
  "mb": 1.08,
  "title": "Selected Anthropometric Dimensions of Naval Aviation Personnel (NAMRL-1141, 1971)"
 },
 {
  "name": "historic-australian__DST-Group-GD-0968.pdf",
  "url": "https://www.dst.defence.gov.au/sites/default/files/publications/documents/DST-Group-GD-0968.pdf",
  "mb": 1.77,
  "title": "DST-Group-GD-0968 (DST)"
 },
 {
  "name": "additional__ADA103181.pdf",
  "url": "https://archive.org/download/DTIC_ADA103181/DTIC_ADA103181.pdf",
  "mb": 2.45,
  "title": "A Comparison of Selected International Anthropometric Measurements"
 },
 {
  "name": "ansur-1988__ANSUR-TR89-027.pdf",
  "url": "https://tools.openlab.psu.edu/publicData/ANSUR-TR89-027.pdf",
  "mb": 2.78,
  "title": "NATICK/TR-89/027 interim summary (ODL mirror)"
 },
 {
  "name": "additional__AD0020542.pdf",
  "url": "https://archive.org/download/DTIC_AD0020542/DTIC_AD0020542.pdf",
  "mb": 2.99,
  "title": "Women's Air Force (WAF) basic trainees, WADC TR 53-12"
 },
 {
  "name": "naval-aviators-1964__AD0626322.pdf",
  "url": "https://archive.org/download/DTIC_AD0626322/DTIC_AD0626322.pdf",
  "mb": 3.11,
  "title": "NAEC-ACEL-533 (DTIC)"
 },
 {
  "name": "additional__AD0450836.pdf",
  "url": "https://archive.org/download/DTIC_AD0450836/DTIC_AD0450836.pdf",
  "mb": 3.15,
  "title": "Royal Thai Armed Forces, 1964"
 },
 {
  "name": "caesar__ADA406704.pdf",
  "url": "https://archive.org/download/DTIC_ADA406704/DTIC_ADA406704.pdf",
  "mb": 3.23,
  "title": "Vol. I, AFRL-HE-WP-TR-2002-0169 (DTIC)"
 },
 {
  "name": "additional__AD0710202.pdf",
  "url": "https://archive.org/download/DTIC_AD0710202/DTIC_AD0710202.pdf",
  "mb": 3.39,
  "title": "Anthropometry of the Air Force Female Hand. AMRL-TR-69-26"
 },
 {
  "name": "ansur-1988__ADA224986.pdf",
  "url": "https://archive.org/download/DTIC_ADA224986/DTIC_ADA224986.pdf",
  "mb": 3.53,
  "title": "ANSUR 1988 correlations and regressions (NATICK/TR-90/032)"
 },
 {
  "name": "latin-american-armed-forces__AD0759949.pdf",
  "url": "https://archive.org/download/DTIC_AD0759949/DTIC_AD0759949.pdf",
  "mb": 3.54,
  "title": "USATTC 7209002 (DTIC)"
 },
 {
  "name": "iran-1969-71__AD0728822.pdf",
  "url": "https://archive.org/download/DTIC_AD0728822/DTIC_AD0728822.pdf",
  "mb": 3.75,
  "title": "Phase III Technical Summary (DTIC)"
 },
 {
  "name": "korea__AD0661625.pdf",
  "url": "https://archive.org/download/DTIC_AD0661625/DTIC_AD0661625.pdf",
  "mb": 4.68,
  "title": "AD0661625 (DTIC)"
 },
 {
  "name": "usaf-1967__ADA168485.pdf",
  "url": "https://archive.org/download/DTIC_ADA168485/DTIC_ADA168485.pdf",
  "mb": 4.78,
  "title": "AAMRL-TR-85-062 survey history (DTIC)"
 },
 {
  "name": "ansur-ii-2012__ADA498172.pdf",
  "url": "https://archive.org/download/DTIC_ADA498172/DTIC_ADA498172.pdf",
  "mb": 5.09,
  "title": "ANSUR II pilot study"
 },
 {
  "name": "ansur-ii-2012__ADA548497.pdf",
  "url": "https://archive.org/download/DTIC_ADA548497/DTIC_ADA548497.pdf",
  "mb": 5.22,
  "title": "Measurer's Handbook NATICK/TR-11/017 (DTIC)"
 },
 {
  "name": "ansur-ii-2012__ANSURII-TR11-017.pdf",
  "url": "https://tools.openlab.psu.edu/publicData/ANSURII-TR11-017.pdf",
  "mb": 5.22,
  "title": "Measurer's Handbook NATICK/TR-11/017 (ODL copy)"
 },
 {
  "name": "dod-hdbk-743a-nasa-rp-1024__19790005541.pdf",
  "url": "https://ntrs.nasa.gov/api/citations/19790005541/downloads/19790005541.pdf",
  "mb": 5.53,
  "title": "NASA RP-1024 Vol. III (NTRS)"
 },
 {
  "name": "caesar__ADA406674.pdf",
  "url": "https://archive.org/download/DTIC_ADA406674/DTIC_ADA406674.pdf",
  "mb": 5.62,
  "title": "AFRL-HE-WP-TR-2002-0170 (DTIC)"
 },
 {
  "name": "us-army-women-1977__ADA043715.pdf",
  "url": "https://archive.org/download/DTIC_ADA043715/DTIC_ADA043715.pdf",
  "mb": 5.8,
  "title": "Report 1, NATICK/TR-77/021 (DTIC)"
 },
 {
  "name": "ansur-ii-2012__ADA634277.pdf",
  "url": "https://archive.org/download/DTIC_ADA634277/DTIC_ADA634277.pdf",
  "mb": 6.86,
  "title": "2012 US Army pilot survey: 977 men, 42 women (NATICK/TR-16/013)"
 },
 {
  "name": "ansur-ii-2012__ADA611869.pdf",
  "url": "https://archive.org/download/DTIC_ADA611869/DTIC_ADA611869.pdf",
  "mb": 7.33,
  "title": "NATICK/TR-15/007 (DTIC)"
 },
 {
  "name": "ansur-ii-2012__ANSURII-TR15-007.pdf",
  "url": "https://tools.openlab.psu.edu/publicData/ANSURII-TR15-007.pdf",
  "mb": 7.33,
  "title": "NATICK/TR-15/007 (ODL copy)"
 },
 {
  "name": "mc-ansur-2010__ADA581918.pdf",
  "url": "https://archive.org/download/DTIC_ADA581918/DTIC_ADA581918.pdf",
  "mb": 7.43,
  "title": "NATICK/TR-13/018 (DTIC)"
 },
 {
  "name": "awas__DSTO-TR-3006.pdf",
  "url": "https://www.dst.defence.gov.au/sites/default/files/publications/documents/DSTO-TR-3006.pdf",
  "mb": 7.75,
  "title": "DSTO-TR-3006 (DST)"
 },
 {
  "name": "awas__ADA610792.pdf",
  "url": "https://archive.org/download/DTIC_ADA610792/DTIC_ADA610792.pdf",
  "mb": 7.84,
  "title": "DSTO-TR-3006 (DTIC)"
 },
 {
  "name": "german-air-force-1967-68__ADA010674.pdf",
  "url": "https://archive.org/download/DTIC_ADA010674/DTIC_ADA010674.pdf",
  "mb": 8.49,
  "title": "AGARD-AG-205 (DTIC)"
 },
 {
  "name": "usaf-1967__ADA010674.pdf",
  "url": "https://archive.org/download/DTIC_ADA010674/DTIC_ADA010674.pdf",
  "mb": 8.49,
  "title": "AGARD-AG-205 (DTIC)"
 },
 {
  "name": "additional__ADA310612.pdf",
  "url": "https://archive.org/download/DTIC_ADA310612/DTIC_ADA310612.pdf",
  "mb": 8.94,
  "title": "Canadian Forces matched database validation (NATICK/TR-96/031)"
 },
 {
  "name": "additional__ADA239831.pdf",
  "url": "https://archive.org/download/DTIC_ADA239831/DTIC_ADA239831.pdf",
  "mb": 9.62,
  "title": "1946 US Army men and women surveys (105,062 men; 8,864 women)"
 },
 {
  "name": "ansur-1988__ADA222782.pdf",
  "url": "https://archive.org/download/DTIC_ADA222782/DTIC_ADA222782.pdf",
  "mb": 9.62,
  "title": "ANSUR 1988 bivariate frequency tables (NATICK/TR-90/031)"
 },
 {
  "name": "usaf-1950__AD0047953.pdf",
  "url": "https://archive.org/download/DTIC_AD0047953/DTIC_AD0047953.pdf",
  "mb": 10.85,
  "title": "WADC TR 52-321 (DTIC)"
 },
 {
  "name": "us-army-women-1977__ADA048591.pdf",
  "url": "https://archive.org/download/DTIC_ADA048591/DTIC_ADA048591.pdf",
  "mb": 10.88,
  "title": "Report 5 (DTIC)"
 },
 {
  "name": "us-army-women-1977__ADA044806.pdf",
  "url": "https://archive.org/download/DTIC_ADA044806/DTIC_ADA044806.pdf",
  "mb": 12.27,
  "title": "Report 2, NATICK/TR-77/024 (DTIC)"
 },
 {
  "name": "usmc-1966__ADA073824.pdf",
  "url": "https://archive.org/download/DTIC_ADA073824/DTIC_ADA073824.pdf",
  "mb": 13.34,
  "title": "CEMEL-115 (DTIC)"
 },
 {
  "name": "us-army-men-1966__AD0743465.pdf",
  "url": "https://archive.org/download/DTIC_AD0743465/DTIC_AD0743465.pdf",
  "mb": 13.88,
  "title": "TR 72-51-CE (DTIC)"
 },
 {
  "name": "asran-2015__DST-Group-TR-3564_0.pdf",
  "url": "https://www.dst.defence.gov.au/sites/default/files/publications/documents/DST-Group-TR-3564_0.pdf",
  "mb": 14.23,
  "title": "DST-Group-TR-3564 (DST)"
 },
 {
  "name": "dod-hdbk-743a-nasa-rp-1024__DOD-HDBK-743A_anthro_handbook.pdf",
  "url": "http://mreed.umtri.umich.edu/mreed/documents/DOD-HDBK-743A_anthro_handbook.pdf",
  "mb": 14.56,
  "title": "DOD-HDBK-743A (UMTRI)"
 },
 {
  "name": "additional__ADA074807.pdf",
  "url": "https://archive.org/download/DTIC_ADA074807/DTIC_ADA074807.pdf",
  "mb": 16.16,
  "title": "Robinette et al. (1979). A Comparison of Male and Female Body Sizes and Proportions. AMRL-TR-79-69"
 },
 {
  "name": "nzdfas__56.pdf",
  "url": "https://ojs.aut.ac.nz/tuwhera-open-monographs/1/catalog/download/7/12/56",
  "mb": 18.76,
  "title": "Monograph PDF (AUT Tuwhera)"
 },
 {
  "name": "ansur-1988__ADA225094.pdf",
  "url": "https://archive.org/download/DTIC_ADA225094/DTIC_ADA225094.pdf",
  "mb": 25.51,
  "title": "NATICK/TR-89/044 (DTIC)"
 },
 {
  "name": "ansur-1988__ADA241952.pdf",
  "url": "https://archive.org/download/DTIC_ADA241952/DTIC_ADA241952.pdf",
  "mb": 29.58,
  "title": "ANSUR 1988 pilot summary statistics (NATICK/TR-91/040)"
 },
 {
  "name": "additional__ADA529930.pdf",
  "url": "https://archive.org/download/DTIC_ADA529930/DTIC_ADA529930.pdf",
  "mb": 48.44,
  "title": "Anthropometry: A Bibliography with Abstracts (useful for finding accession numbers for unverified rows)"
 },
 {
  "name": "ansur-1988__ANSUR-TR89-044.pdf",
  "url": "https://tools.openlab.psu.edu/publicData/ANSUR-TR89-044.pdf",
  "mb": 65.08,
  "title": "NATICK/TR-89/044 (ODL mirror)"
 },
 {
  "name": "usaf-women-1968__AD0743113.pdf",
  "url": "https://archive.org/download/DTIC_AD0743113/DTIC_AD0743113.pdf",
  "mb": 69.26,
  "title": "AMRL-TR-70-5 (DTIC)"
 },
 {
  "name": "dod-hdbk-743a-nasa-rp-1024__ADA473152.pdf",
  "url": "https://archive.org/download/DTIC_ADA473152/DTIC_ADA473152.pdf",
  "mb": 74.68,
  "title": "NASA RP-1024 Vol. II (DTIC)"
 }
];

function importPapers() {
  const folder = DriveApp.getFolderById(FOLDER_ID);
  const have = {};
  const it = folder.getFiles();
  while (it.hasNext()) have[it.next().getName()] = true;
  const started = Date.now();
  let saved = 0, skipped = 0, tooBig = [], failed = [];
  for (const p of PAPERS) {
    if (have[p.name]) { skipped++; continue; }
    if (Date.now() - started > 5 * 60 * 1000) { Logger.log('Time budget reached; run again to continue.'); break; }
    if (p.mb > 50) { tooBig.push(p); continue; }
    try {
      const res = UrlFetchApp.fetch(p.url, { muteHttpExceptions: true, followRedirects: true });
      const blob = res.getBlob();
      if (res.getResponseCode() !== 200 || blob.getBytes().length < 2000 || blob.getContentType().indexOf('html') >= 0) {
        failed.push(p); continue;
      }
      folder.createFile(blob.setName(p.name));
      saved++;
    } catch (e) { failed.push(p); }
  }
  Logger.log('saved ' + saved + ', already there ' + skipped + ', too big for Apps Script ' + tooBig.length + ', failed ' + failed.length);
  tooBig.forEach(p => Logger.log('TOO BIG (' + p.mb + ' MB), download manually: ' + p.url));
  failed.forEach(p => Logger.log('FAILED: ' + p.url));
}
