import json, shutil
from pathlib import Path
REPO = Path(__file__).resolve().parents[2]
old=json.load(open("out/calib.json")); meta1=json.load(open("out/meta.json")); lm=json.load(open("out/lm2.json"))
rnd=lambda v: round(v,1); out={}
for t in "MF":
    D=old[t]; N=lm["OUT"][t]
    sprite={k:{kk:rnd(vv) for kk,vv in meta1[t+"_"+k].items()} for k in ("stand","sit")}
    sprite.update({k:{kk:rnd(vv) for kk,vv in v.items()} for k,v in N["sprites"].items()})
    out[t]=dict(sprite=sprite,
                runs={int(k):[[rnd(a),rnd(b)] for a,b in v] for k,v in D["runs"].items() if int(k)%4==0 or 236<=int(k)<=300 or 80<=int(k)<=140},
                tw={int(k):v for k,v in D["tw"].items()}, td={int(k):v for k,v in D["td"].items()},
                ts={int(k):v for k,v in N["ts"].items()}, dxs=N["dxs"], L=D["L"], G=D["G"],
                arms=N["arms"], head=N["head"], wall=N["wall"], legfoot=N["legfoot"])
out["FR"]=lm["FR"]
js="// Landmarks, silhouettes and survey proportions for the body map (see site/img/body). Generated by scripts/body_sprites; SVG units, 440 per stature.\nexport const DATA = "+json.dumps(out,separators=(",",":"))+";\n"
open(str(REPO / "site" / "js" / "bodydata.js"),"w").write(js); print(len(js))
for t in "MF":
    for p in ("stand","sit","stand_side","stand_back","reach","up","situp","sitleg"): shutil.copy(f"out/{t}_{p}.webp",str(REPO / "site" / "img" / "body" / f"{t}_{p}.webp"))
